### ISSUE TITLE
Run Command As (RCA)

### ISSUE THREAD

**Issue by ghost** [survanetwork/AllSigns#17]
### 💭 What should be added or changed regarding this plugin?

Being able of changing the permission of the player, for example i want to remove the capability of using /shop on the entire world except in the shop, but there is no way except if i rund the /shop as OP with a sign and removing the permission of /shop for everyone, at the moment this is not possible, and i want to suggest it

**Comment by jarne** [comment]
Thanks for your suggestions, this has been added to version 2 which will be released soon!
