### ISSUE TITLE
Crashes the server

### ISSUE THREAD

**Issue by wearewaveshapers** [survanetwork/AllSigns#32]
### Immediately crashes the server when using "#as"

Crash Archive: 

https://crash.pmmp.io/view/9855739

**Comment by jarne** [comment]
I think that's a Windows path related issue I fixed here (0662310), however I forgot to create a release after fixing it. There's a new version available now including the fix. Please try the latest version, PHAR available from here: https://static.surva.net/osplugins/dl/AllSigns2.0.7.phar
